создание пользователя в банке
msk-itstep-org/jv1911-aleshin pull request #1
Opened 2019-12-02 14:35 UTC by Ilyaaleshin1992

2019-12-02 14:42 UTC, const-se requested changes
Выполните исправления и запушьте их в эту же ветку task-1, они сами подтянутся в данный Pull Request

2019-12-02 14:42 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Account.java
> +    private User user_id;
Нет-нет-нет. Здесь у нас не база данных.
Свойство класса должно называться просто user, раз уж в этом свойстве хранится объект класса User, а не айдишник пользователя.
Переименовать свойство можно очень быстро - Shift+F6

2019-12-02 14:42 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/User.java
> +    @OneToMany(targetEntity = Account.class, mappedBy = "user_id")
Нужно будет не забыть после переименования свойства Account.user переименовать и здесь mappedBy

2019-12-02 14:42 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/User.java
> +    public Set<Account> getAccounts() {
А почему для accounts есть геттер, но нет сеттера?

2019-12-02 14:42 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Account.java
> +    private int balance = 0;
На самом деле баланс в счете не хранится. Баланс вычисляется на основе проделанных операций. Я бы лучше убрал это свойство (и соответствующий столбец таблицы тоже)

2019-12-02 14:42 UTC, const-se commented on src/main/java/org/itstep/msk/app/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Integer> {
А где репозиторий для Account?

2019-12-02 17:45 UTC, const-se requested changes
Еще чуть-чуть правок, и тогда можно будет принять пулреквест

2019-12-02 17:45 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Account.java
> +    @JoinColumn(name = "parent", referencedColumnName = "id")
Не согласен с таким названием. Parent - это родитель. А тут у нас "хозяин". Лучше было бы owner. И в базе всяким внешним ключам мы-таки добавляем суффикс _id.
Предлагаю сделать следующим образом:
Столбец в таблице назвать owner_id, а свойство в классе - owner.

2019-12-02 17:45 UTC, const-se commented on src/main/resources/db/migration/V1.3__perent.sql
> +ALTER TABLE account ADD COLUMN parent INT NOT NULL REFERENCES user (id);
Как я уже написал в комментарии к классу Account, давай в итоге переименуем столбец в owner_id.
И не обязательно дропать старый столбец, его достаточно переименовать вот так:
`ALTER TABLE account CHANGE parent owner_id INT NOT NULL REFERENCES user (id);`

2019-12-02 18:04 UTC, Ilyaaleshin1992 commented on src/main/java/org/itstep/msk/app/entity/Account.java
> +    @JoinColumn(name = "parent", referencedColumnName = "id")
ок

2019-12-03 09:04 UTC, const-se approved these changes
Идеально!

2019-12-03 09:04 UTC, merged